codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: false  # disable the default status that measures entire project
        tests:  # declare a new status context "tests"
          target: 100%  # we always want 100% coverage here
          paths: "mpesa_api/tests/"  # only include coverage in "tests/" folder
        app:  # declare a new status context "app"
          paths: "!mpesa_api/tests/"  # remove all files in "tests/"
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
