# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2CRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phone", models.BigIntegerField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "conversation_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "originator_conversation_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "response_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "response_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "result_type",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "result_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "result_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transaction_receipt",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "working_funds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "utility_funds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "paod_account_funds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "mpesa_user_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_registered_customer",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "B2C Requests",
                "db_table": "tbl_b2c_requests",
            },
        ),
    ]
