# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_b2crequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2crequest",
            name="error_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="b2crequest",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="b2crequest",
            name="request_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
