# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20171105_0351"),
    ]

    operations = [
        migrations.RenameField(
            model_name="b2crequest",
            old_name="paod_account_funds",
            new_name="paid_account_funds",
        ),
    ]
