# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_c2brequests"),
    ]

    operations = [
        migrations.RenameModel(old_name="C2bRequests", new_name="C2BRequest",),
    ]
