# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20171106_2339"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="c2brequest", name="transaction_id",
        ),
    ]
