# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_onlinecheckout"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinecheckout",
            name="account_reference",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="onlinecheckout",
            name="transaction_description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onlinecheckout",
            name="checkout_request_id",
            field=models.CharField(default="", max_length=20),
        ),
    ]
