# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20171119_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="type",
            field=models.CharField(default="c2b", max_length=3),
            preserve_default=False,
        ),
    ]
