# Generated by Django 3.0.8 on 2020-07-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_authtoken_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecheckout',
            name='is_paybill',
            field=models.BooleanField(default=True),
        ),
    ]
